# Generated by Django 3.2.3 on 2021-05-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortMsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
